<script lang="ts">
	import { Select as SelectPrimitive } from "bits-ui";
	import SelectPortal from "./select-portal.svelte";
	import SelectScrollUpButton from "./select-scroll-up-button.svelte";
	import SelectScrollDownButton from "./select-scroll-down-button.svelte";
	import { cn, type WithoutChild } from "$lib/utils.js";
	import type { ComponentProps } from "svelte";
	import type { WithoutChildrenOrChild } from "$lib/utils.js";

	let {
		ref = $bindable(null),
		class: className,
		sideOffset = 4,
		portalProps,
		children,
		preventScroll = true,
		...restProps
	}: WithoutChild<SelectPrimitive.ContentProps> & {
		portalProps?: WithoutChildrenOrChild<ComponentProps<typeof SelectPortal>>;
	} = $props();

	// LOCAL CHANGE — re-apply if this file is ever regenerated by the shadcn CLI.
	//
	// bits-ui makes the *viewport* the scroll container: it sets
	// `position:relative; flex:1; overflow:auto` inline, and all of its scroll
	// logic (canScrollUp/Down, scrollTop) drives `viewportNode`. That `flex:1`
	// only means something inside a bounded flex column, so the content below is
	// `flex flex-col` with a real `max-h`. As shipped it was neither: the content
	// had `overflow-y-auto` but no height bound — and `overflow-y:auto` on a box
	// that is free to grow can never produce a scrollbar — so a long option list
	// simply ran off the bottom of the screen.
	//
	// The bound is bits-ui's own `--bits-select-content-available-height` (the
	// space the floating layer measured between the trigger and the viewport
	// edge), capped at 18rem to match `Command.List`'s `max-h-72` so the dropdown
	// and multiselect filters agree. The variable reads as `undefinedpx` until
	// the first measurement, but the floating layer parks the content off-page
	// (`translate(0,-200%)`) until it is positioned, so that frame is never seen.
	//
	// The viewport also had a height utility bound to the select anchor-height
	// variable. That was dropped: it pinned the list to the *trigger's* height,
	// which fights the `flex:1` above. Do not name that utility literally here —
	// Tailwind scans comments too, and would emit the dead rule again.
</script>

<SelectPortal {...portalProps}>
	<SelectPrimitive.Content
		bind:ref
		{sideOffset}
		{preventScroll}
		data-slot="select-content"
		class={cn(
			"bg-popover text-popover-foreground data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 ring-foreground/10 min-w-36 rounded-md shadow-md ring-1 duration-100 data-[side=inline-start]:slide-in-from-right-2 data-[side=inline-end]:slide-in-from-left-2 relative isolate z-50 flex flex-col overflow-hidden max-h-[min(18rem,var(--bits-select-content-available-height))]",
			className
		)}
		{...restProps}
	>
		<SelectScrollUpButton />
		<SelectPrimitive.Viewport
			class={cn(
				"w-full min-w-(--bits-select-anchor-width) scroll-my-1"
			)}
		>
			{@render children?.()}
		</SelectPrimitive.Viewport>
		<SelectScrollDownButton />
	</SelectPrimitive.Content>
</SelectPortal>
